version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: stockapp-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-stockapp}"]
      interval: 5s
      timeout: 3s
      retries: 20

  
  web:
    container_name: stockapp-frontend
    build:
      context: ./frontend/packages/NextAuth
      dockerfile: Dockerfile.frontend
      target: dev
    ports:
      - "3000:3000"
      - "5555:5555" # Prisma Studio Port
    env_file:
      - ./frontend/packages/NextAuth/.env
      - ./.env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@db:5432/${POSTGRES_DB:-stockapp}
    depends_on:
      db:
          condition: service_healthy
    volumes:
      - ./frontend/packages/NextAuth:/app         # hot reload in dev
      - /app/node_modules        # keep container’s node_modules isolated
      - /app/.next

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: stockapp-backend
    env_file:
      - ./.env
      - ./backend/.env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@db:5432/${POSTGRES_DB:-stockapp}
      # MONGO_URI: mongodb://admin:password@mongo:27017/stockapp?authSource=admin
      MONGO_URI: mongodb://${MONGO_USER:-admin}:${MONGO_PASSWORD:-password}@mongo:27017/${MONGO_DB:-stockapp}?authSource=admin
      # MONGODB_URL: mongodb://${MONGO_USER:-admin}:${MONGO_PASSWORD:-password}@mongo:27017/${MONGO_DB:-stockapp}?authSource=admin
      # Choose your framework here: fastapi or flask
      BACKEND_FRAMEWORK: ${BACKEND_FRAMEWORK:-fastapi}
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mongo
      # - redis
    volumes:
      - ./backend/app:/app/app  # hot reload mount (dev)

    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    # Command that overrides the default command in Dockerfile.backend. Just use for dev. 
    # command: >
    #   sh -c "uvicorn app.adapters.db.mongo:app --host 0.0.0.0 --port 8000 --reload"

    

  mongo:
    image: mongo:7.0
    container_name: stockapp-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-password}
      MONGO_INITDB_DATABASE: ${MONGO_DB:-stockapp}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      # - ./mongo-init:/docker-entrypoint-initdb.d  # Optional: for initialization scripts
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # celery worker (for async tasks)
  worker:
    build: 
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: stockapp-celery-worker
    env_file: .env
    command: >
      celery -A app.tasks.celery_app
      worker -Q default,low,high --loglevel=INFO
    volumes:
      - ./backend:/app/app:rw
    depends_on:
      redis:
        condition: service_healthy
      mongo:
        condition: service_healthy


  # celery beat (for periodic tasks)
  beat:
    build: 
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: stockapp-celery-beat
    env_file: .env
    command: >
      celery -A app.tasks.celery_app
      beat --loglevel=INFO
    volumes:
      - ./backend:/app/app:rw
    depends_on:
      redis:
        condition: service_healthy
      mongo:
        condition: service_healthy
    # Optional: uncomment if you plan periodic tasks
    deploy:
      replicas: 0

  

  redis:
    image: redis:7-alpine
    container_name: stockapp-redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
  mongo_data:
